import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Archive, ArrowLeft, Bell, ChevronLeft, ChevronRight, CircleAlert, Download, FileClock, Plus, RefreshCw, Search, Settings2, SlidersHorizontal, X } from "lucide-react";
import { HERMES_BASE_PATH } from "@/lib/api";
import { crm, CrmError, editableLead, serializeLeadInput, type Business, type FieldDefinition, type Lead, type LeadInput, type LeadStatus, type ListArgs, type Notification, type Source } from "@/lib/crm";

const businesses: Business[] = ["dj_wedding", "real_estate", "other"];
const statuses: LeadStatus[] = ["new", "contacted", "qualified", "proposal", "won", "lost"];
const businessLabel: Record<Business, string> = { dj_wedding: "DJ / Wedding", real_estate: "Real estate", other: "Other" };
const title = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
const auditValue = (value: unknown) => value === null || value === undefined || value === "" ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value);
const dateText = (value?: string | number) => value ? new Date(typeof value === "number" && value < 1e11 ? value * 1000 : value).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : "—";
const blankLead = (): LeadInput => ({ name: "", email: "", phone: "", company: "", source_id: "", external_id: "", business: "other", lead_type: "", status: "new", assigned_agent: "", estimated_value: "", currency: "USD", acquisition_date: "", action_timeframe: "", next_action_date: "", wedding_date: "", custom_fields: {} });
const message = (error: unknown) => error instanceof Error ? error.message : String(error);
const isConflict = (error: unknown) => error instanceof CrmError && /conflict|revision/i.test(error.code + error.message);

function Control({ label, children }: { label: string; children: ReactNode }) {
  return <label className="crm-label">{label}{children}</label>;
}
function Select({ value, onChange, children, disabled }: { value: string; onChange: (value: string) => void; children: ReactNode; disabled?: boolean }) {
  return <select className="crm-input" value={value} disabled={disabled} onChange={e => onChange(e.target.value)}>{children}</select>;
}
function AgentSelect({ value, onChange, roster, includeAll = false }: { value: string; onChange: (v: string) => void; roster: string[]; includeAll?: boolean }) {
  return <Select value={value} onChange={onChange}><option value="">{includeAll ? "All agents" : "Unassigned"}</option>{value && !roster.includes(value) && <option value={value}>{value} (not in roster)</option>}{roster.map(agent => <option key={agent} value={agent}>{agent.replace(/^agent-/, "")}</option>)}</Select>;
}
function Empty({ heading, text, action }: { heading: string; text: string; action?: ReactNode }) {
  return <div className="flex min-h-48 flex-col items-center justify-center gap-2 px-6 py-12 text-center"><div className="mb-2 rounded-full border border-current/20 p-3"><FileClock size={19} /></div><strong>{heading}</strong><p className="crm-muted max-w-sm text-sm">{text}</p>{action}</div>;
}
function Skeleton() { return <div className="crm-panel space-y-5 p-6" aria-busy="true" aria-label="Loading CRM"><div className="crm-skeleton h-6 w-1/3" />{[1,2,3,4,5].map(i => <div key={i} className="crm-skeleton h-10" style={{ width: `${95-i*8}%` }} />)}</div>; }
function ErrorBlock({ text, retry }: { text: string; retry: () => void }) { return <div className="crm-panel flex flex-wrap items-center gap-3 p-5 text-sm" role="alert"><CircleAlert size={19} /><span className="flex-1">{text}</span><button className="crm-btn" onClick={retry}><RefreshCw size={14} /> Retry</button></div>; }
function Modal({ title: heading, close, children }: { title: string; close: () => void; children: ReactNode }) {
  useEffect(() => {
    const key = (e: KeyboardEvent) => { if (e.key === "Escape") close(); };
    window.addEventListener("keydown", key);
    return () => window.removeEventListener("keydown", key);
  }, [close]);
  return <div className="crm-modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><section className="crm-modal" role="dialog" aria-modal="true" aria-label={heading}><div className="mb-6 flex items-start justify-between gap-4"><div><div className="crm-kicker">CRM / WORKSPACE</div><h2 className="mt-2 text-2xl font-bold tracking-tight">{heading}</h2></div><button className="crm-btn !p-2" onClick={close} aria-label="Close"><X size={17} /></button></div>{children}</section></div>;
}

function LeadEditor({ initial, fields, sources, roster, save, close, busy, error, conflict, reloadLatest }: { initial?: Lead; fields: FieldDefinition[]; sources: Source[]; roster: string[]; save: (lead: LeadInput) => void; close: () => void; busy: boolean; error: string; conflict: boolean; reloadLatest: () => void }) {
  const [form, setForm] = useState<LeadInput>(() => initial ? editableLead(initial) : blankLead());
  const set = <K extends keyof LeadInput>(key: K, value: LeadInput[K]) => setForm(prev => ({ ...prev, [key]: value }));
  const custom = (field: FieldDefinition, value: string | boolean | null) => set("custom_fields", { ...form.custom_fields, [field.id]: value === "" ? null : field.type === "number" && value !== null ? Number(value) : value });
  const submit = (e: FormEvent) => { e.preventDefault(); save(serializeLeadInput(form, initial ? "update" : "create", initial?.estimated_value)); };
  return <Modal title={initial ? `Edit ${initial.name}` : "New lead"} close={close}>
    <form onSubmit={submit} className="space-y-6">
      <div className="grid gap-4 sm:grid-cols-2">
        <Control label="Full name"><input className="crm-input" value={form.name} onChange={e => set("name", e.target.value)} placeholder="Name, email or phone required" /></Control>
        <Control label="Business *"><Select value={form.business} onChange={v => set("business", v as Business)}>{businesses.map(b => <option key={b} value={b}>{businessLabel[b]}</option>)}</Select></Control>
        <Control label="Email"><input className="crm-input" type="email" value={form.email || ""} onChange={e => set("email", e.target.value)} /></Control>
        <Control label="Phone"><input className="crm-input" type="tel" value={form.phone || ""} onChange={e => set("phone", e.target.value)} /></Control>
        <Control label="Company"><input className="crm-input" value={form.company || ""} onChange={e => set("company", e.target.value)} /></Control>
        <Control label="Lead type"><input className="crm-input" placeholder="e.g. Wedding reception, buyer" value={form.lead_type || ""} onChange={e => set("lead_type", e.target.value)} /></Control>
        <Control label="Status"><Select value={form.status} onChange={v => set("status", v as LeadStatus)}>{statuses.map(s => <option key={s} value={s}>{title(s)}</option>)}</Select></Control>
        <Control label="Assigned agent"><AgentSelect value={form.assigned_agent || ""} onChange={v => set("assigned_agent", v)} roster={roster} /></Control>
        <Control label="Source"><Select value={form.source_id || ""} onChange={v => set("source_id", v)}><option value="">Manual / unknown</option>{sources.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</Select></Control>
        <Control label="External ID"><input className="crm-input" value={form.external_id || ""} onChange={e => set("external_id", e.target.value)} /></Control>
        <Control label="Estimated value"><input className="crm-input" type="number" min="0" step="0.01" value={form.estimated_value || ""} onChange={e => set("estimated_value", e.target.value)} /></Control>
        <Control label="Currency"><input className="crm-input" maxLength={3} pattern="[A-Za-z]{3}" value={form.currency || ""} onChange={e => set("currency", e.target.value.toUpperCase())} /></Control>
        <Control label="Acquisition date"><input className="crm-input" type="date" value={form.acquisition_date || ""} onChange={e => set("acquisition_date", e.target.value)} /></Control>
        <Control label="Action timeframe"><input className="crm-input" placeholder="e.g. Within 2 weeks" value={form.action_timeframe || ""} onChange={e => set("action_timeframe", e.target.value)} /></Control>
        <Control label="Next action date"><input className="crm-input" type="date" value={form.next_action_date || ""} onChange={e => set("next_action_date", e.target.value)} /></Control>
        <Control label="Wedding date"><input className="crm-input" type="date" value={form.wedding_date || ""} onChange={e => set("wedding_date", e.target.value)} /></Control>
      </div>
      {fields.length > 0 && <div className="border-t pt-5" style={{ borderColor: "var(--crm-line)" }}><div className="crm-kicker mb-4">CUSTOM FIELDS</div><div className="grid gap-4 sm:grid-cols-2">{fields.map(f => <Control key={f.id} label={`${f.label}${f.required ? " *" : ""}`}>{f.type === "boolean" ? <Select value={String(form.custom_fields?.[f.id] ?? "")} onChange={v => custom(f, v === "" ? null : v === "true")}><option value="">Not set</option><option value="true">Yes</option><option value="false">No</option></Select> : f.type === "select" ? <Select value={String(form.custom_fields?.[f.id] ?? "")} onChange={v => custom(f, v)}><option value="">Select…</option>{f.options?.map(o => <option key={o}>{o}</option>)}</Select> : <input className="crm-input" type={f.type === "number" ? "number" : f.type === "date" ? "date" : "text"} required={f.required} value={String(form.custom_fields?.[f.id] ?? "")} onChange={e => custom(f, e.target.value)} />}</Control>)}</div></div>}
      {error && <div role="alert" className="text-sm text-red-400">{conflict && <strong>This lead changed elsewhere. </strong>}{error}{conflict && <button type="button" className="crm-btn ml-2" onClick={reloadLatest}>Load latest revision</button>}</div>}
      <div className="flex justify-end gap-2 border-t pt-5" style={{ borderColor: "var(--crm-line)" }}><button type="button" className="crm-btn" onClick={close}>Cancel</button><button type="submit" className="crm-btn crm-btn-primary" disabled={busy}>{busy ? "Saving…" : initial ? "Save changes" : "Create lead"}</button></div>
    </form>
  </Modal>;
}

function LeadDetail({ lead, fields, sources, roster, refresh, onBack, onEdit, run, busy, error, conflict }: { lead: Lead; fields: FieldDefinition[]; sources: Source[]; roster: string[]; refresh: () => void; onBack: () => void; onEdit: () => void; run: (action: string, args: Record<string, unknown>) => Promise<unknown>; busy: boolean; error: string; conflict: boolean }) {
  const [note, setNote] = useState("");
  const [notePage, setNotePage] = useState(1);
  const [historyPage, setHistoryPage] = useState(1);
  const [noteData, setNoteData] = useState<{ items: NonNullable<Lead["notes"]>; total: number } | null>(null);
  const [historyData, setHistoryData] = useState<{ items: NonNullable<Lead["history"]>; total: number } | null>(null);
  const [activityError, setActivityError] = useState("");
  const [activityReload, setActivityReload] = useState(0);
  useEffect(() => { setNotePage(1); setHistoryPage(1); }, [lead.id]);
  useEffect(() => { let active = true; crm<{ items: NonNullable<Lead["notes"]>; total: number }>("notes", { id: lead.id, page: notePage, limit: 20 }).then(result => { if (active) { setNoteData(result); setActivityError(""); } }).catch(e => { if (active) setActivityError(message(e)); }); return () => { active = false; }; }, [lead.id, lead.revision, notePage, activityReload]);
  useEffect(() => { let active = true; crm<{ items: NonNullable<Lead["history"]>; total: number }>("history", { id: lead.id, page: historyPage, limit: 20 }).then(result => { if (active) { setHistoryData(result); setActivityError(""); } }).catch(e => { if (active) setActivityError(message(e)); }); return () => { active = false; }; }, [lead.id, lead.revision, historyPage, activityReload]);
  const source = sources.find(s => s.id === lead.source_id);
  const mutate = async (action: string, extra: Record<string, unknown> = {}) => { const result = await run(action, { id: lead.id, revision: lead.revision, ...extra }); if (result && action === "note") setNote(""); };
  return <div className="space-y-5">
    <button className="crm-btn" onClick={onBack}><ArrowLeft size={15} /> All leads</button>
    <div className="crm-panel p-5 sm:p-7">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="crm-kicker">LEAD / {lead.id}</div><h2 className="mt-2 text-2xl font-bold tracking-tight sm:text-3xl">{lead.name}</h2><div className="mt-3 flex flex-wrap gap-2"><span className="crm-pill">{businessLabel[lead.business] || title(lead.business)}</span><span className="crm-pill">{title(lead.status)}</span>{lead.archived && <span className="crm-pill">Archived</span>}</div></div><div className="flex flex-wrap gap-2"><button className="crm-btn" onClick={onEdit}>Edit details</button><button className="crm-btn" disabled={busy || lead.archived} onClick={() => { if (window.confirm(`Archive ${lead.name}? This removes the lead from the active list.`)) void mutate("archive"); }}><Archive size={14} /> Archive</button></div></div>
      {lead.duplicate_ids && lead.duplicate_ids.length > 0 && <div className="mt-5 rounded border border-amber-500/30 bg-amber-500/10 p-3 text-sm">Possible related contacts: {lead.duplicate_ids.join(", ")}. Review before merging opportunities.</div>}
      {error && <div role="alert" className="mt-4 rounded border border-red-400/30 p-4 text-sm"><strong>{conflict ? "This lead changed elsewhere." : "Could not save."}</strong> {error} {conflict && <button className="crm-btn ml-2" onClick={refresh}>Load latest revision</button>}</div>}
      <div className="mt-7 grid gap-6 border-t pt-6 md:grid-cols-[1fr_1fr]" style={{ borderColor: "var(--crm-line)" }}>
        <div className="space-y-5"><div className="crm-kicker">CONTACT & OPPORTUNITY</div><dl className="grid grid-cols-2 gap-x-3 gap-y-5 text-sm">{([["Email", lead.email ? <a href={`mailto:${lead.email}`} className="underline">{lead.email}</a> : "—"], ["Phone", lead.phone ? <a href={`tel:${lead.phone}`} className="underline">{lead.phone}</a> : "—"], ["Company", lead.company], ["Lead type", lead.lead_type], ["Source", source?.name || lead.source_id], ["External ID", lead.external_id], ["Estimated value", lead.estimated_value ? `${lead.currency || "USD"} ${lead.estimated_value}` : ""], ["Acquired", lead.acquisition_date], ["Timeframe", lead.action_timeframe], ["Next action", lead.next_action_date], ["Wedding date", lead.wedding_date], ["Last updated", dateText(lead.updated_at)]] as Array<[string, ReactNode]>).map(([label, value]) => <div key={label}><dt className="crm-kicker !tracking-wider">{label}</dt><dd className="mt-1 break-words">{value || "—"}</dd></div>)}</dl></div>
        <div className="space-y-5"><div><Control label="ASSIGNED AGENT"><AgentSelect value={lead.assigned_agent || ""} roster={roster} onChange={v => void mutate("assign", { assigned_agent: v })} /></Control></div><div><Control label="STATUS"><Select value={lead.status} onChange={v => void mutate("status", { status: v })}>{statuses.map(s => <option key={s} value={s}>{title(s)}</option>)}</Select></Control></div>{fields.length > 0 && <div><div className="crm-kicker mb-3">CUSTOM FIELDS</div><dl className="grid grid-cols-2 gap-3 text-sm">{fields.map(f => <div key={f.id}><dt className="crm-muted">{f.label}</dt><dd className="font-semibold">{lead.custom_fields?.[f.id] == null ? "—" : String(lead.custom_fields[f.id])}</dd></div>)}</dl></div>}</div>
      </div>
    </div>
    {activityError && <ErrorBlock text={activityError} retry={() => setActivityReload(k => k + 1)} />}
    <div className="grid gap-5 lg:grid-cols-2"><section className="crm-panel p-5"><div className="crm-kicker mb-4">NOTES · {noteData?.total ?? lead.notes_total ?? 0}</div><form onSubmit={async e => { e.preventDefault(); if (note.trim()) { await mutate("note", { text: note.trim() }); setNotePage(1); } }} className="mb-5 space-y-2"><textarea className="crm-input min-h-24 resize-y" placeholder="Add context for the team…" value={note} onChange={e => setNote(e.target.value)} /><button className="crm-btn crm-btn-primary" disabled={!note.trim() || busy}>Add note</button></form><div className="space-y-3">{noteData ? noteData.items.length ? noteData.items.map((n, i) => <div key={n.id || i} className="border-t pt-3 text-sm" style={{ borderColor: "var(--crm-line)" }}><div className="crm-muted mb-1 text-xs">{n.actor || n.author || "Team member"} · {dateText(n.created_at)}</div><p className="whitespace-pre-wrap break-words">{n.text}</p></div>) : <p className="crm-muted text-sm">No notes yet. Add the first update above.</p> : <Skeleton />}</div><Pager page={notePage} total={noteData?.total || 0} limit={20} change={setNotePage} /></section>
    <section className="crm-panel p-5"><div className="crm-kicker mb-4">CHANGE HISTORY · {historyData?.total ?? lead.history_total ?? 0}</div><div className="space-y-4">{historyData ? historyData.items.length ? historyData.items.map((h, i) => <div key={h.id || i} className="relative border-l pl-4 text-sm" style={{ borderColor: "var(--crm-line)" }}><strong>{title(h.action || "Updated")}</strong><div className="crm-muted text-xs">{h.actor || "System"} · {dateText(h.at || h.created_at || h.timestamp)}</div>{h.changes && Object.entries(h.changes).map(([field, change]) => <div key={field} className="crm-muted mt-1 break-words text-xs"><strong>{title(field)}</strong>: {auditValue(change.old)} → {auditValue(change.new)}</div>)}</div>) : <p className="crm-muted text-sm">No changes recorded yet.</p> : <Skeleton />}</div><Pager page={historyPage} total={historyData?.total || 0} limit={20} change={setHistoryPage} /></section></div>
  </div>;
}

function Pager({ page, total, limit, change }: { page: number; total: number; limit: number; change: (page: number) => void }) {
  if (total <= limit) return null;
  return <div className="mt-5 flex items-center justify-end gap-2 border-t pt-3 text-xs" style={{ borderColor: "var(--crm-line)" }}><button className="crm-btn !min-h-8" disabled={page <= 1} onClick={() => change(page - 1)}><ChevronLeft size={14} /> Previous</button><span>{page} / {Math.ceil(total / limit)}</span><button className="crm-btn !min-h-8" disabled={page >= Math.ceil(total / limit)} onClick={() => change(page + 1)}>Next <ChevronRight size={14} /></button></div>;
}

export default function CrmPage() {
  const [tab, setTab] = useState<"leads" | "sources" | "fields" | "notifications">("leads");
  const [roster, setRoster] = useState<string[]>([]);
  const [sources, setSources] = useState<Source[]>([]);
  const [fields, setFields] = useState<FieldDefinition[]>([]);
  const [summary, setSummary] = useState<{ total: number; by_business: Record<string, number>; by_status: Record<string, number> } | null>(null);
  const [list, setList] = useState<{ items: Lead[]; total: number; page: number; limit: number } | null>(null);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [notificationPage, setNotificationPage] = useState(1);
  const [notificationTotal, setNotificationTotal] = useState(0);
  const [filters, setFilters] = useState<ListArgs>({ query: "", business: "", status: "", source_id: "", assigned_agent: "", archived: false, page: 1, limit: 20 });
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<Lead | null>(null);
  const [editor, setEditor] = useState<Lead | "new" | null>(null);
  const [loading, setLoading] = useState(true);
  const [listLoading, setListLoading] = useState(true);
  const [error, setError] = useState("");
  const [actionError, setActionError] = useState("");
  const [conflict, setConflict] = useState(false);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const [refreshKey, setRefreshKey] = useState(0);
  const refresh = useCallback(() => setRefreshKey(k => k + 1), []);
  const updateFilter = <K extends keyof ListArgs>(key: K, value: ListArgs[K]) => setFilters(f => ({ ...f, [key]: value, page: 1 }));
  useEffect(() => { const timer = window.setTimeout(() => updateFilter("query", search), 280); return () => clearTimeout(timer); }, [search]);
  useEffect(() => {
    let active = true;
    setLoading(true);
    Promise.all([crm<{ items: Source[] }>("sources"), crm<{ items: FieldDefinition[] }>("fields"), crm<typeof summary>("summary"), crm<{ items: Array<{ agent: string; role: string }> }>("roster")])
      .then(([s, f, totals, members]) => { if (!active) return; setSources((s.items || []).map(source => ({ ...source, instructions: source.instructions || source.setup, auth_requirements: source.auth_requirements || source.authentication, example_payload: source.example_payload || source.example, last_test_status: source.last_delivery_ok === true ? "Authenticated delivery accepted" : source.last_delivery_ok === false ? `Delivery rejected${source.last_error ? `: ${source.last_error}` : ""}` : "Not tested" }))); setFields(f.items || []); setSummary(totals); setRoster((members.items || []).map(member => member.agent).filter(Boolean)); setError(""); })
      .catch(e => { if (active) setError(message(e)); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [refreshKey]);
  useEffect(() => {
    let active = true;
    setListLoading(true);
    crm<{ items: Lead[]; total: number; page: number; limit: number }>("list", Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== "")))
      .then(result => { if (active) { setList(result); setError(""); } })
      .catch(e => { if (active) setError(message(e)); }).finally(() => { if (active) setListLoading(false); });
    return () => { active = false; };
  }, [filters, refreshKey]);
  useEffect(() => { if (tab !== "notifications") return; let active = true; crm<{ items: Notification[]; total: number }>("notifications", { page: notificationPage, limit: 30 }).then(r => { if (active) { setNotifications(r.items || []); setNotificationTotal(r.total || 0); setError(""); } }).catch(e => { if (active) setError(message(e)); }); return () => { active = false; }; }, [tab, refreshKey, notificationPage]);
  const loadSelected = useCallback(async () => { if (!selected) return; try { setSelected(await crm<Lead>("get", { id: selected.id })); setActionError(""); setConflict(false); refresh(); } catch (e) { setActionError(message(e)); } }, [selected?.id, refresh]);
  const run = async (action: string, args: Record<string, unknown>): Promise<unknown> => {
    setBusy(true); setActionError(""); setConflict(false);
    try { const result = await crm<unknown>(action, args); if (["create", "update", "note", "assign", "status", "archive"].includes(action) && result && typeof result === "object" && "id" in result && "revision" in result) setSelected(result as Lead); setNotice("Saved"); refresh(); return result; }
    catch (e) { setActionError(message(e)); setConflict(isConflict(e)); return null; }
    finally { setBusy(false); }
  };
  const [createKey, setCreateKey] = useState(() => crypto.randomUUID());
  const saveLead = async (lead: LeadInput) => {
    const result = await run(editor === "new" ? "create" : "update", editor === "new" ? { lead, idempotency_key: createKey } : { id: (editor as Lead).id, revision: (editor as Lead).revision, changes: lead });
    if (result && editor === "new") setCreateKey(crypto.randomUUID());
    if (result) { setSelected(result as Lead); setEditor(null); }
  };
  const selectLead = async (lead: Lead) => { setSelected(lead); setActionError(""); try { setSelected(await crm<Lead>("get", { id: lead.id })); } catch (e) { setActionError(message(e)); } };
  const exportData = async () => { const snapshot = await run("export", {}); if (!snapshot) return; const blob = new Blob([JSON.stringify(snapshot, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `crm-export-${new Date().toISOString().slice(0,10)}.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const totalPages = Math.max(1, Math.ceil((list?.total || 0) / filters.limit));
  const tabItems = [{ id: "leads", label: "Leads", icon: Search }, { id: "sources", label: "Sources & routing", icon: SlidersHorizontal }, { id: "fields", label: "Custom fields", icon: Settings2 }, { id: "notifications", label: "Delivery health", icon: Bell }] as const;
  const sourceName = (id?: string) => sources.find(s => s.id === id)?.name || id || "Manual";
  return <main className="crm-workspace mx-auto w-full max-w-[1480px] min-h-[100dvh] pb-16">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4 border-b pb-6" style={{ borderColor: "var(--crm-line)" }}><div><div className="crm-kicker mb-2">FLEET / SHARED WORKSPACE</div><h1 className="crm-title">Lead desk<span className="opacity-35">.</span></h1><p className="crm-muted mt-2 text-sm">One record of every opportunity, from first inquiry to follow-through.</p></div><div className="flex flex-wrap gap-2"><button className="crm-btn" onClick={refresh} aria-label="Refresh CRM"><RefreshCw size={15} /> Refresh</button><button className="crm-btn" onClick={() => void exportData()} disabled={busy}><Download size={15} /> Export</button><button className="crm-btn crm-btn-primary" onClick={() => { setActionError(""); setEditor("new"); }}><Plus size={16} /> New lead</button></div></div>
    {notice && <div role="status" className="mb-4 flex items-center justify-between rounded border border-current/20 px-3 py-2 text-sm">{notice}<button onClick={() => setNotice("")} aria-label="Dismiss notification"><X size={14} /></button></div>}
    {error && <div className="mb-5"><ErrorBlock text={error} retry={refresh} /></div>}
    {loading && !summary && <div className="mb-5"><Skeleton /></div>}
    <div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6"><div className="crm-panel col-span-2 px-5 py-4 sm:col-span-1"><div className="crm-kicker">TOTAL LEADS</div><div className="mt-2 text-3xl font-bold tabular-nums">{summary?.total ?? "—"}</div></div>{businesses.map(b => <button key={b} className="crm-panel px-4 py-4 text-left transition-opacity hover:opacity-75" onClick={() => { setTab("leads"); updateFilter("business", b); setSelected(null); }}><div className="crm-kicker">{businessLabel[b]}</div><div className="mt-2 text-2xl font-bold tabular-nums">{summary?.by_business?.[b] ?? 0}</div></button>)}<div className="crm-panel col-span-2 px-4 py-4"><div className="crm-kicker">PIPELINE</div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm">{statuses.map(s => <span key={s}>{title(s)} <strong className="tabular-nums">{summary?.by_status?.[s] ?? 0}</strong></span>)}</div></div></div>
    <div className="mb-6 flex gap-6 overflow-x-auto border-b" style={{ borderColor: "var(--crm-line)" }} role="tablist" aria-label="CRM sections">{tabItems.map(item => <button key={item.id} className="crm-tab flex shrink-0 items-center gap-2" role="tab" aria-selected={tab === item.id} onClick={() => { setTab(item.id); setSelected(null); setActionError(""); }}><item.icon size={15} />{item.label}</button>)}</div>
    {tab === "leads" && (selected ? <LeadDetail key={selected.id} lead={selected} fields={fields} sources={sources} roster={roster} refresh={() => void loadSelected()} onBack={() => setSelected(null)} onEdit={() => { setActionError(""); setEditor(selected); }} run={run} busy={busy} error={actionError} conflict={conflict} /> : <div className="space-y-4"><div className="crm-panel grid gap-3 p-4 md:grid-cols-3 xl:grid-cols-[2fr_repeat(4,1fr)]"><Control label="SEARCH"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3 opacity-50" size={16} /><input className="crm-input !pl-9" placeholder="Name, email, company…" value={search} onChange={e => setSearch(e.target.value)} /></div></Control><Control label="BUSINESS"><Select value={filters.business || ""} onChange={v => updateFilter("business", v)}><option value="">All businesses</option>{businesses.map(b => <option key={b} value={b}>{businessLabel[b]}</option>)}</Select></Control><Control label="STATUS"><Select value={filters.status || ""} onChange={v => updateFilter("status", v)}><option value="">All statuses</option>{statuses.map(s => <option key={s} value={s}>{title(s)}</option>)}</Select></Control><Control label="SOURCE"><Select value={filters.source_id || ""} onChange={v => updateFilter("source_id", v)}><option value="">All sources</option>{sources.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</Select></Control><Control label="ASSIGNEE"><AgentSelect value={filters.assigned_agent || ""} onChange={v => updateFilter("assigned_agent", v)} roster={roster} includeAll /></Control><label className="flex items-center gap-2 text-xs md:col-span-3 xl:col-span-5"><input type="checkbox" checked={!!filters.archived} onChange={e => updateFilter("archived", e.target.checked)} /> Show archived leads</label></div>
    {listLoading && !list ? <Skeleton /> : <section className="crm-panel overflow-hidden">{listLoading && <div className="crm-kicker px-4 pt-3">UPDATING RESULTS…</div>}{list?.items.length ? <><div className="overflow-x-auto"><table className="crm-table"><thead><tr><th>Contact</th><th>Business / type</th><th>Status</th><th>Source</th><th>Assigned to</th><th>Next action</th><th></th></tr></thead><tbody>{list.items.map(lead => <tr key={lead.id}><td><button className="text-left font-semibold hover:underline" onClick={() => void selectLead(lead)}>{lead.name}</button><div className="crm-muted text-xs">{lead.email || lead.phone || lead.company || lead.id}</div></td><td>{businessLabel[lead.business] || title(lead.business)}<div className="crm-muted text-xs">{lead.lead_type || "—"}</div></td><td><span className="crm-pill"><span className="crm-dot" />{title(lead.status)}</span></td><td>{sourceName(lead.source_id)}</td><td>{lead.assigned_agent?.replace(/^agent-/, "") || <span className="crm-muted">Unassigned</span>}</td><td>{lead.next_action_date || "—"}</td><td><button className="crm-btn !min-h-8" onClick={() => void selectLead(lead)}>Open <ChevronRight size={13} /></button></td></tr>)}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 border-t p-4 text-xs" style={{ borderColor: "var(--crm-line)" }}><span className="crm-muted">Showing {(filters.page - 1) * filters.limit + 1}–{Math.min(filters.page * filters.limit, list.total)} of {list.total}</span><div className="flex items-center gap-2"><button className="crm-btn !min-h-8" disabled={filters.page <= 1} onClick={() => setFilters(f => ({ ...f, page: f.page - 1 }))}><ChevronLeft size={14} /> Previous</button><span className="px-2">Page {filters.page} / {totalPages}</span><button className="crm-btn !min-h-8" disabled={filters.page >= totalPages} onClick={() => setFilters(f => ({ ...f, page: f.page + 1 }))}>Next <ChevronRight size={14} /></button></div></div></> : <Empty heading="No leads in this view" text="Try removing a filter, or create the first lead to start the record." action={<button className="crm-btn crm-btn-primary mt-3" onClick={() => setEditor("new")}><Plus size={15} /> New lead</button>} />}</section>}</div>)}
    {tab === "sources" && <><BusinessRouting roster={roster} /><div className="mt-6"><SourcesPanel sources={sources} roster={roster} run={run} busy={busy} error={actionError} /></div></>}
    {tab === "fields" && <FieldsPanel fields={fields} run={run} busy={busy} error={actionError} />}
    {tab === "notifications" && <section className="crm-panel overflow-hidden"><div className="flex items-center justify-between p-5"><div><h2 className="text-lg font-bold">Notification outbox</h2><p className="crm-muted text-xs">Failed, retrying and unassigned deliveries stay visible until resolved.</p></div><button className="crm-btn" onClick={refresh}><RefreshCw size={14} /> Refresh</button></div>{notifications.length ? <div className="overflow-x-auto"><table className="crm-table"><thead><tr><th>Lead</th><th>Recipient</th><th>State</th><th>Attempts</th><th>Last update</th><th>Recovery</th></tr></thead><tbody>{notifications.map(n => <tr key={n.id}><td><button className="font-semibold underline" onClick={async () => { setTab("leads"); try { setSelected(await crm<Lead>("get", { id: n.lead_id })); } catch (e) { setError(message(e)); } }}>{n.lead_id}</button></td><td>{n.recipient || "Unassigned"}</td><td><span className="crm-pill"><span className="crm-dot" />{title(n.status)}</span>{n.error && <div className="mt-1 max-w-xs break-words text-xs text-red-400">{n.error}</div>}</td><td>{n.attempts}</td><td>{dateText(n.updated_at)}</td><td><button className="crm-btn !min-h-8" disabled={busy || n.status === "delivered"} onClick={() => void run("retry", { id: n.id })}><RefreshCw size={13} /> Retry</button></td></tr>)}</tbody></table></div> : <Empty heading="No deliveries to review" text="New lead notifications and their delivery attempts will appear here." />}{actionError && <p role="alert" className="p-4 text-sm text-red-400">{actionError}</p>}</section>}
    {tab === "notifications" && notificationTotal > 30 && <div className="mt-3 flex items-center justify-end gap-2 text-xs"><span className="crm-muted">{notificationTotal} deliveries · Page {notificationPage} of {Math.ceil(notificationTotal / 30)}</span><button className="crm-btn" disabled={notificationPage <= 1} onClick={() => setNotificationPage(n => n - 1)}><ChevronLeft size={14} /> Previous</button><button className="crm-btn" disabled={notificationPage >= Math.ceil(notificationTotal / 30)} onClick={() => setNotificationPage(n => n + 1)}>Next <ChevronRight size={14} /></button></div>}
    {editor && <LeadEditor key={editor === "new" ? "new" : `${editor.id}:${editor.revision}`} initial={editor === "new" ? undefined : editor} fields={fields} sources={sources} roster={roster} save={saveLead} close={() => setEditor(null)} busy={busy} error={actionError} conflict={conflict} reloadLatest={async () => { if (!editor || editor === "new") return; try { const latest = await crm<Lead>("get", { id: editor.id }); setEditor(latest); setSelected(latest); setActionError(""); setConflict(false); } catch (e) { setActionError(message(e)); } }} />}
  </main>;
}

function BusinessRouting({ roster }: { roster: string[] }) {
  const [settings, setSettings] = useState<{ revision: number; business_routing: Record<string, string> } | null>(null);
  const [route, setRoute] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [saved, setSaved] = useState(false);
  const reload = useCallback(() => {
    setLoading(true);
    crm<{ revision: number; business_routing: Record<string, string> }>("settings")
      .then(data => { setSettings(data); setRoute({ ...data.business_routing }); setError(""); })
      .catch(e => setError(message(e))).finally(() => setLoading(false));
  }, []);
  useEffect(() => { reload(); }, [reload]);
  return <section className="crm-panel p-5"><div className="mb-4"><div className="crm-kicker">DEFAULT ROUTING</div><h2 className="mt-1 text-lg font-bold">Business recipients</h2><p className="crm-muted mt-1 text-xs">Fallback when a lead has no explicit assignee and its source has no recipient. Blank means visibly unassigned.</p></div>
    {loading && !settings ? <Skeleton /> : <><div className="grid gap-3 md:grid-cols-3">{businesses.map(b => <Control key={b} label={businessLabel[b]}><AgentSelect roster={roster} value={route[b] || ""} onChange={v => { setSaved(false); setRoute(prev => ({ ...prev, [b]: v })); }} /></Control>)}</div><div className="mt-4 flex items-center gap-3"><button className="crm-btn crm-btn-primary" disabled={busy || !settings} onClick={async () => { if (!settings) return; setBusy(true); setSaved(false); try { const result = await crm<typeof settings>("settings_save", { revision: settings.revision, business_routing: route }); setSettings(result); setRoute({ ...result.business_routing }); setSaved(true); setError(""); } catch (e) { setError(message(e)); } finally { setBusy(false); } }}>{busy ? "Saving…" : "Save routing"}</button>{saved && <span className="text-xs" role="status">Routing saved</span>}</div></>}
    {error && <div role="alert" className="mt-3 text-sm text-red-400">{error} <button className="crm-btn ml-2" onClick={reload}>Reload latest</button></div>}
  </section>;
}

function SourcesPanel({ sources, roster, run, busy, error }: { sources: Source[]; roster: string[]; run: (action: string, args: Record<string, unknown>) => Promise<unknown>; busy: boolean; error: string }) {
  const [editing, setEditing] = useState<Source | "new" | null>(null);
  const [secret, setSecret] = useState("");
  const [copied, setCopied] = useState(false);
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="crm-muted max-w-2xl text-sm">Sources start unconnected. Choose a business and a recipient explicitly; a website name alone does not determine routing.</p><button className="crm-btn crm-btn-primary" onClick={() => setEditing("new")}><Plus size={15} /> Add source</button></div>{sources.length ? <div className="grid gap-4 lg:grid-cols-2">{sources.map(source => <article key={source.id} className="crm-panel p-5"><div className="flex items-start justify-between gap-3"><div><div className="crm-kicker">{source.id}</div><h2 className="mt-1 text-lg font-bold">{source.name}</h2><p className="crm-muted text-xs">{source.domain || "Custom source"}</p></div><span className="crm-pill"><span className="crm-dot" />{source.connected ? "Delivery seen" : "Unconnected"}</span></div><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><div className="crm-kicker">BUSINESS</div><div className="mt-1">{source.business ? businessLabel[source.business] : "Not configured"}</div></div><div><div className="crm-kicker">ROUTE TO</div><div className="mt-1">{source.assigned_agent || "Unassigned"}</div></div><div><div className="crm-kicker">LATEST DELIVERY</div><div className="mt-1">{dateText(source.last_delivery_at)}</div></div><div><div className="crm-kicker">TEST STATUS</div><div className="mt-1">{source.last_test_status || source.test_status || "Not tested"}</div></div></div><div className="mt-5 flex flex-wrap gap-2"><button className="crm-btn" onClick={() => setEditing(source)}><Settings2 size={14} /> Configure & setup</button><button className="crm-btn" disabled={busy} onClick={async () => { if (!window.confirm(`Rotate the secret for ${source.name}? The old secret will stop working immediately.`)) return; const result = await run("source_rotate_secret", { id: source.id }) as { secret?: string } | null; if (result?.secret) setSecret(result.secret); }}>Rotate secret</button></div></article>)}</div> : <Empty heading="No sources configured" text="Add a source to define its payload mapping and agent routing." />}{error && <p className="text-sm text-red-400" role="alert">{error}</p>}
  {editing && <SourceEditor key={editing === "new" ? "new" : editing.id} initial={editing === "new" ? undefined : editing} roster={roster} close={() => setEditing(null)} save={async args => { const result = await run("source_save", args); if (result) setEditing(null); }} busy={busy} error={error} />}
  {secret && <Modal title="New source secret" close={() => setSecret("")}><div className="space-y-4 text-sm"><p>Copy this secret now. It is shown only once; store it on your trusted server, never in browser-side code.</p><code className="crm-panel block break-all p-4">{secret}</code><button className="crm-btn crm-btn-primary" onClick={async () => { await navigator.clipboard.writeText(secret); setCopied(true); }}>{copied ? "Copied" : "Copy secret"}</button></div></Modal>}</div>;
}
function SourceEditor({ initial, roster, close, save, busy, error }: { initial?: Source; roster: string[]; close: () => void; save: (args: Record<string, unknown>) => void; busy: boolean; error: string }) {
  const [id, setId] = useState(initial?.id || "");
  const [name, setName] = useState(initial?.name || "");
  const [business, setBusiness] = useState(initial?.business || "");
  const [agent, setAgent] = useState(initial?.assigned_agent || "");
  const [enabled, setEnabled] = useState(initial?.enabled ?? false);
  const [mapping, setMapping] = useState<Record<string, string>>(initial?.mapping || {});
  const keys = ["name","email","phone","company","business","lead_type","external_id","estimated_value","currency","acquisition_date","action_timeframe","next_action_date","wedding_date"];
  const webhook = `${window.location.origin}${HERMES_BASE_PATH}/api/crm/webhook/${encodeURIComponent(id || "source-id")}`;
  const example = JSON.stringify(initial?.example_payload || { event_id: "example-unique-submission-id", lead: { name: "Sample inquiry", email: "sample@example.invalid", business: business || "other", lead_type: "Inquiry" } }, null, 2);
  return <Modal title={initial ? `Configure ${initial.name}` : "Add a source"} close={close}><form onSubmit={e => { e.preventDefault(); save({ id, revision: initial?.revision, name, business: business || undefined, assigned_agent: agent || "", mapping: Object.fromEntries(Object.entries(mapping).filter(([,v]) => v.trim())), enabled }); }} className="space-y-6"><div className="grid gap-4 sm:grid-cols-2"><Control label="Source ID *"><input className="crm-input" required pattern="[a-z0-9_-]+" disabled={!!initial} value={id} onChange={e => setId(e.target.value.toLowerCase())} placeholder="website-name" /></Control><Control label="Display name *"><input className="crm-input" required value={name} onChange={e => setName(e.target.value)} /></Control><Control label="Business routing"><Select value={business} onChange={setBusiness}><option value="">Not set</option>{businesses.map(b => <option key={b} value={b}>{businessLabel[b]}</option>)}</Select></Control><Control label="Notify agent"><AgentSelect value={agent} onChange={setAgent} roster={roster} /></Control></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} /> Enable inbound delivery</label>
  <div className="border-t pt-5" style={{ borderColor: "var(--crm-line)" }}><div className="crm-kicker mb-1">FIELD MAPPING</div><p className="crm-muted mb-4 text-xs">For providers sending flat JSON, map each lead field to a top-level payload key. The generic format uses the nested lead object below.</p><div className="grid gap-3 sm:grid-cols-2">{keys.map(key => <Control key={key} label={title(key)}><input className="crm-input" placeholder="Payload key (optional)" value={mapping[key] || ""} onChange={e => setMapping(m => ({ ...m, [key]: e.target.value }))} /></Control>)}</div></div>
  <div className="border-t pt-5 text-sm" style={{ borderColor: "var(--crm-line)" }}><div className="crm-kicker mb-3">CONNECTION GUIDE</div><p className="crm-muted mb-2">Use a trusted server-to-server integration. Verify whether this provider supports webhooks before connecting. Never put the bearer secret in client JavaScript.</p><div className="space-y-2"><div>Endpoint <code className="break-all">{webhook}</code></div><div>Method <code>POST</code> · JSON · <code>Authorization: Bearer &lt;source-secret&gt;</code></div><div>Each delivery needs a stable, unique <code>event_id</code>; replaying it will not create another lead.</div>{initial?.instructions && <p>{initial.instructions}</p>}{initial?.auth_requirements && <p>{initial.auth_requirements}</p>}<div className="crm-kicker pt-3">SAFE EXAMPLE PAYLOAD</div><pre className="crm-raised overflow-x-auto rounded p-3 text-xs">{example}</pre><div>Connection status: <strong>{initial?.connected ? "Delivery seen" : "Not connected"}</strong> · Last test: {initial?.last_test_status || initial?.test_status || "Not run"}</div></div></div>{error && <p role="alert" className="text-sm text-red-400">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="crm-btn" onClick={close}>Cancel</button><button className="crm-btn crm-btn-primary" disabled={busy}>{busy ? "Saving…" : "Save source"}</button></div></form></Modal>;
}
function FieldsPanel({ fields, run, busy, error }: { fields: FieldDefinition[]; run: (action: string, args: Record<string, unknown>) => Promise<unknown>; busy: boolean; error: string }) {
  const [editing, setEditing] = useState<FieldDefinition | "new" | null>(null);
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="crm-muted text-sm">Define typed values once; they appear on every lead and in agent field discovery.</p><button className="crm-btn crm-btn-primary" onClick={() => setEditing("new")}><Plus size={15} /> Add field</button></div><section className="crm-panel overflow-hidden">{fields.length ? <table className="crm-table"><thead><tr><th>Field</th><th>Key</th><th>Type</th><th>Required</th><th></th></tr></thead><tbody>{fields.map(f => <tr key={f.id}><td className="font-semibold">{f.label}</td><td><code>{f.id}</code></td><td>{title(f.type)}{f.options?.length ? ` · ${f.options.join(", ")}` : ""}</td><td>{f.required ? "Yes" : "No"}</td><td><button className="crm-btn !min-h-8" onClick={() => setEditing(f)}>Edit</button></td></tr>)}</tbody></table> : <Empty heading="No custom fields" text="Add fields for information unique to your lead process." />}</section>{error && <p role="alert" className="text-sm text-red-400">{error}</p>}{editing && <FieldEditor initial={editing === "new" ? undefined : editing} close={() => setEditing(null)} busy={busy} error={error} save={async field => { if (await run("field_save", field as unknown as Record<string, unknown>)) setEditing(null); }} />}</div>;
}
function FieldEditor({ initial, close, save, busy, error }: { initial?: FieldDefinition; close: () => void; save: (field: FieldDefinition) => void; busy: boolean; error: string }) {
  const [field, setField] = useState<FieldDefinition>(initial || { id: "", label: "", type: "string", required: false, options: [] });
  const [options, setOptions] = useState((initial?.options || []).join("\n"));
  return <Modal title={initial ? `Edit ${initial.label}` : "New custom field"} close={close}><form className="space-y-4" onSubmit={e => { e.preventDefault(); save({ ...field, options: field.type === "select" ? options.split("\n").map(x => x.trim()).filter(Boolean) : [] }); }}><Control label="Field key *"><input className="crm-input" pattern="[a-z][a-z0-9_]*" required disabled={!!initial} value={field.id} onChange={e => setField(f => ({ ...f, id: e.target.value.toLowerCase() }))} placeholder="event_venue" /></Control><Control label="Label *"><input className="crm-input" required value={field.label} onChange={e => setField(f => ({ ...f, label: e.target.value }))} /></Control><Control label="Value type"><Select value={field.type} disabled={!!initial} onChange={v => setField(f => ({ ...f, type: v as FieldDefinition["type"] }))}>{["string","number","boolean","date","select"].map(t => <option value={t} key={t}>{title(t)}</option>)}</Select></Control>{field.type === "select" && <Control label="Choices (one per line)"><textarea className="crm-input min-h-28" required value={options} onChange={e => setOptions(e.target.value)} /></Control>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={field.required || false} onChange={e => setField(f => ({ ...f, required: e.target.checked }))} /> Required on new leads</label>{error && <p role="alert" className="text-sm text-red-400">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="crm-btn" onClick={close}>Cancel</button><button className="crm-btn crm-btn-primary" disabled={busy}>Save field</button></div></form></Modal>;
}